services:
  - type: web
    name: mandarjyotishkendra-blog
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /admin/*
        destination: /index.html
